### ISSUE TITLE
Broken Crucible Recipes

### ISSUE THREAD

**Issue by Shorepion** [Quarris/EidolonDataRecipes#1]
-Minecraft 1.16.5
-Forge 36.2.21
-Tested Modpack1: Magica Infinitum III - v3.3.6 (https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii/files/3600238)
-Tested Modpack2: Custom private instance with only Eidolon and Eidolon Data Recipes installed (+JEI as helping tool)
-eidolon-0.2.7
-eidolonrecipes-1.1
-Singleplayer and Multiplayer affected

After testing 'Eidolon Data Recipes' in enabled and disabled state, it turns out that if enabled every Crucible recipe that has more than 1 stir in a row in one step (for example: 'Essence of Death, 'Lesser Soul Gem', 'Leather'...), doesn't work/will fail. 
The last ingredient, in the last step always got consumed instead of turning into the crafting result.

Videos trying to craft the 'Essence of Death' and 'Leather' as examples:
Essence of Death:
https://user-images.githubusercontent.com/24994890/148935481-ef51d050-d707-493e-8193-67b67711a622.mp4

Leather:
https://user-images.githubusercontent.com/24994890/148936087-76c809ed-84ee-48da-945d-191e1cb507fe.mp4

**Comment by Quarris** [comment]
I found the issue. The issue isnt with stirs but its with defining ingredients with count like so
![image](https://user-images.githubusercontent.com/6171764/148943925-fd45f643-82d0-45e1-b925-9a51ca109c93.png)

Eidolon separates these into individual item stacks when throwing them into the cauldron. I'll try and find a solution soon

**Comment by Shorepion** [comment]
Oh okay! Looking forward for that - thanks.

**Comment by Shorepion** [comment]
Ah ok! Thanks

**Comment by Quarris** [comment]
I uploaded v1.3 to curseforge. Please test that and reopen this issue if there are still problems.

**Comment by Shorepion** [comment]
After quick testings it seems to be fixed ✌️
