### ISSUE TITLE
JEI not showing modified recipes on servers/multiplayer right away

### ISSUE THREAD

**Issue by Shorepion** [Quarris/EidolonDataRecipes#2]
-**Minecraft 1.16.5**
-**Forge 36.2.21**
-**Testing Instance:** Custom private instance with Eidolon and Eidolon Data Recipes installed (+JEI)
-**Used Data Pack Loaders:** KubeJS, Global Data & Resourcepacks
-**Modfiles:** jei-1.16.5-7.7.1.139.jar; eidolon-0.2.7.jar; eidolonrecipes-1.3.jar; globaldataandresourcepacks-1.16.5-1.10.2.jar; kubejs-forge-1605.3.19-build.258.jar
-**Multiplayer affected (dedicated servers?)**

_Issue:_
JEI wont show the modified recipes on server, if you start your game and join a server right away without joining a singpleplayer world before.

Tried different scenarios:

_Scenario 1:_
-Start Game
-Join server right away (without going into singleplayer before)
->Result: JEI shows default/unchanged eidolon recipes not the modified one

_Scenario 2:_
-Start Game
-Join Singleplayer world first
-Join server afterwards
->Result: JEI shows modified recipes

_Scenario 3:_
-Start Game
-Join server right away (without going into singleplayer before)
->Result: JEI shows default/unchanged eidolon recipes not the modified one
-Join Singleplayer world
-Ho back to join server
->Result: Result: JEI now shows modified recipes

So joining the singleplayer world before or after joining the server will fix this issue. But this has to be done after every new gamestart

_Each scenario:_
-in every scenario it was possible to craft the modified items, no matter what was showed by JEI
-modified recipes loaded with only KubeJS mod
-modified recipes loaded with only Global Data & Resourcepack mod
-both enabled
->All had the same result described in scenario 1-3.

(-Server and Client had the data pack installed)

**Comment by Quarris** [comment]
From my testing this should be fixed in 1.4, please have a go when you get the chance

**Comment by Shorepion** [comment]
No issues anymore 👍
