### ISSUE TITLE
Can't seem to remove a recipe?

### ISSUE THREAD

**Issue by Elfinlocks** [Quarris/EidolonDataRecipes#3]
Hi there, 

Apologies if this is simply user error, but I'm trying to remove the Soul Enchanter recipe entirely, rather than change it. I replaced the output with "minecraft:air" in the paste, with no luck. Any ideas of how to accomplish this?

https://pastebin.com/9vQUdK2b

This file is located in the following directory in my instance. I know this datapack is good as I'm using it for other modded recipes at this time.

openloader/data/astralengineering/data/eidolon/recipes/worktable/soul_enchanter.json

**Comment by Quarris** [comment]
You can't disable recipe by setting the output to air; instead add a "conditions" array and add type: "forge:false"
You can simply replace the json file with this and it will remove it. This works on any recipe using datapacks, not just from this mod.

```
{
  "type": "minecraft:crafting_shaped"
  "conditions": [
    {
      "type": "forge:false"
    }
  ]
}
```
