### ISSUE TITLE
[v2.2] Recipe Removal Not Functioning

### ISSUE THREAD

**Issue by Elfinlocks** [Quarris/EidolonDataRecipes#4]
Hello, me again, so sorry for all of these posts. I have done some extensive testing on this, so hopefully this helps narrow down the source.

- Firstly, the documentation seems to be incorrect - the datapack path for both v1.4 and v2.2 needs to be "eidolon\recipes\eidolon_worktable\", rather than "eidolon\recipes\worktable" as the github displays. Providing this path is the only way I have successfully added recipes to the worktable. 
- Second, removal of recipes does not seem to function, for unknown reasons, as removals are working fine for other mods. New recipes may be added using the path listed above, but they do not overwrite the existing ones. Please see below for an example:

I have been attempting to remove the Soul Enchanter recipe, as you likely know. Per discussion from the last issue, I have tried the following scripts to remove the recipe. Unfortunately, none of them have succeeded. In addition, I have also tried simply leaving the file blank, as this has also worked for other mods for me (namely, Beyond Earth), though this also provided no effects.

Script 1: Setting type to "eidolon:worktable" - https://pastebin.com/7z4YgEg8
Script 2: Setting type to "eidolon:eidolon_worktable" - https://pastebin.com/AAi48kAx
Script 3: Setting type to "minecraft:crafting_shaped" - https://pastebin.com/wq3QdbU9
Script 4: Test recipe, adds dirt to the output, but does not remove Soul Enchanter recipe - https://pastebin.com/x7jRfJnY

All of the scripts listed share the same file name of "soul_enchanter.json". If you have any ideas of how to resolve, they are much appreciated. Thank you for your time and efforts!

![image](https://user-images.githubusercontent.com/43624750/153631262-d28fc341-ebf3-40ac-88a8-465f4ebe1401.png)

**Comment by Quarris** [comment]
Could you send me the whole log that is made after you load up a world?

**Comment by Quarris** [comment]
I've tested this on a modpack with `eidolonrecipes-2.2.jar` using OpenLoader with path `openloader/data/PACK/data/eidolon/recipes/worktable/soul_enchanter.json`
![image](https://user-images.githubusercontent.com/6171764/153687944-c5aae15b-cf88-4ee8-855b-2e1050840f1e.png)

With the contents of the script you provided

![image](https://user-images.githubusercontent.com/6171764/153687961-ea7572a2-cf84-4ead-9e53-4a8663569ad0.png)

And it removes the recipe.

Could you send me that log and maybe some screenshots of the path from the modpack root folder?

**Comment by Elfinlocks** [comment]
Something odd is definitely going on - I moved the Eidolon section of my datapack (literal copy-paste) into a new instance with just Eidolon, JEI, and the requires dependencies, and it successfully removed the recipe. Copying that back directly into my main instance is causing a breakage somewhere, and I'm wondering if it's a mod incompatibility of some form. I have verified that the mod version between main instance and the test instance do match.

[Here's my latest.log](https://gist.githubusercontent.com/Elfinlocks/7ca1d90fbeb8aeefbf729844b2d3e5cc/raw/1b7300871c0aa6c54eaf2e8f8065032acadc3bbf/latest.log)

The only error I see in it relating is this one: 
[10:51:49] [Render thread/WARN]: Unknown recipe category: eidolon:worktable/eidolon:worktable/soul_enchanter

The full path of my openloader is:
C:\Users\Me\AppData\Roaming\gdlauncher_next\instances\Astral Engineering - Dev\openloader\data\astralengineering\data\eidolon\recipes\worktable

**Comment by Elfinlocks** [comment]
After a LOT of troubleshooting, I finally found the issue here - my custom datapack and custom resource pack shared the same name, which was only messing up some datapack mods, unsure why that is. Regardless, changing the name of the resource pack fixed this issue. Thanks for your patience with me!
