### ISSUE TITLE
Incompability with Eidolon's Hexblades (Crucible) Recipes

### ISSUE THREAD

**Issue by Shorepion** [Quarris/EidolonDataRecipes#5]
-Minecraft 1.16.5
-Forge 36.2.30

-Tested Modpack1: Magica Infinitum III - v3.3.8 (https://www.curseforge.com/minecraft/modpacks/magica-infinitum-iii/files/3631582)
-Tested Modpack2: Custom private instance with only Eidolon, Hexblades and Eidolon Data Recipes installed (+JEI as helping tool)

-eidolon-0.2.7
-eidolonrecipes-1.4

-hexblades-1.16.5-0.0.9.2
-Singleplayer and Multiplayer affected

Issue description:
Hexmetal alloy and Hexed Ingot is not craftable. It fails everytime. Also recipes are not shown in JEI.
Disabling Eidolon Data Recipes fixes the broken crucible recipe and JEI shows the recipe again.

**Comment by Quarris** [comment]
Should be fixed in v2.3 when its uploaded to curseforge.

Reopen this issue if the problem persists
