### ISSUE TITLE
Question about Eidolon recipes

### ISSUE THREAD

**Issue by GalaxyOfZero** [Quarris/EidolonDataRecipes#7]
Hello Quarris im the Modpack dev from Sky Friends and i have a question about Eidolon Data Recipes.
I have some Problems to remove existing recipe, new recipes to add via your mod is realy good, but i can not remove the recipes not even with Crafttweaker. i dont no if your can me help but thanks in advance.

**Comment by Quarris** [comment]
Can you show me how you are trying to remove a recipe right now?

Edit: Also what version of the mod are you using?

**Comment by GalaxyOfZero** [comment]
Over Crafttwekers i use `<recipetype:eidolon:crucible>.removeRecipe(<item:eidolon:ender_call>);`
and the add version is `<recipetype:eidolon:crucible>.addJSONRecipe("ender_call_new,
{
  "type": "eidolon:crucible",
  "result": {
    "item": "eidolon:ender_calx",
    "count": 2
  },
  "steps": [
    {
      "ingredients": [
        {
          "item": "botania:mana_pearls"
        },
        {
          "item": "eidolon:enchanted_ash"
        }
      ]
    }
  ]
});`
i use :
- Eidolon 0.2.7
- Eidolon Data Recipes 2.7
- Botania 1.16.5-420.2

**Comment by Quarris** [comment]
Unfortunately I don't know how crafttweaker removes recipes, there are chances that using crafttweaker is not compatible with removal of recipes. Recipes can be removed using mods such as Open Loader, and you can replace the recipe as a json file

**Comment by GalaxyOfZero** [comment]
i have a little question, i try to replace  this via datapack but Unfortunately  it will not work, have your a idea whats wronk
`Sky friends\openloader\data\Sky-Friends\data\eidolon\recipes`
```
{
  "type": "eidolon:crucible",
  "result": {
    "item": "eidolon:ender_calx",
    "count": 2
  },
  "steps": [
    {
      "ingredients": [
        {
          "item": "botania:mana_pearl"
        },
        {
          "item": "eidolon:enchanted_ash"
        }
      ]
    }
  ]
}
```

**Comment by Quarris** [comment]
Have you made sure the name of the file is the same? Probably `ender_calx.json`. Check the logs to see if there are any errors when loading the recipe
